version: '3.7'

services:
  mysql:
    container_name: moviesP2-mysql
    image: movies2-mysql2
    build:
      context: .
      dockerfile: ./dockerfile.mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      # schema?
    networks:
      - movies-network
    ports:
      - 3306:3306
  app:
    depends_on:
      - mysql
    container_name: moviesP2-app
    image: movies-app2
    build:
      context: .
      dockerfile: ./dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    networks:
      - movies-network
  react:
    depends_on:
      - app
    container_name: movies-react
    image: movies-react
    environment:
      NODE_ENV: production
    ports:
      - 3006:3006
    networks:
      - movies-network

networks:
  movies-network: